In [1]:
import numpy as np

In [2]:
np.random.seed(1)


In [3]:
X = np.random.randn(1, 3, 5, 5)

In [4]:
W = np.random.randn(2, 3, 3, 3)
b = np.zeros(2)

padding = 1
stride = 1

In [5]:
X_pad = np.pad(
    X,
    ((0,0), (0,0), (padding,padding), (padding,padding))
)

N, C, H, W_in = X.shape
F, _, KH, KW = W.shape

H_out = (H + 2*padding - KH)//stride + 1
W_out = (W_in + 2*padding - KW)//stride + 1


In [6]:
cols = []

for n in range(N):
    for i in range(0, H_out):
        for j in range(0, W_out):
            patch = X_pad[
                n,
                :,
                i*stride:i*stride+KH,
                j*stride:j*stride+KW
            ]
            cols.append(patch.reshape(-1))

cols = np.array(cols)


In [7]:
W_col = W.reshape(F, -1)


In [8]:
output = cols @ W_col.T


In [9]:
output = output + b

In [10]:
output = output.reshape(N, H_out, W_out, F)
output = output.transpose(0, 3, 1, 2)

print("Output shape:", output.shape)
print(output)


Output shape: (1, 2, 5, 5)
[[[[  2.4551271    0.28985059  -0.60792129   0.57641695  -0.95756779]
   [ -2.35524113  -5.92426458  -3.03706113   2.10939964   3.46178803]
   [  3.58663889   3.79391322  -1.28366011  -0.74392741   5.28139262]
   [ -4.05638172  -5.21296467   2.48967772   3.85642307   2.32681651]
   [  0.11666859   5.50152058   0.28186885   3.79312375  -1.27444046]]

  [[ -2.5214464    2.34447379   2.65707765  -2.56900878   0.6540563 ]
   [ -1.37062674   0.27504184   7.34214959   1.34312947  -2.0437973 ]
   [  1.39106764  -2.25840893   0.68444764   6.75339996  -2.24276255]
   [  5.3019538   -1.97127608  -1.68960001 -10.16266276  11.08333379]
   [  2.61780097  -1.15301055  -3.94369746  -4.02727871   3.08956576]]]]
